# Generated by Django 3.2.6 on 2021-08-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startop',
            old_name='subtitle',
            new_name='description',
        ),
    ]
